"""Stable persisted domain values shared by models and API schemas."""

from enum import StrEnum


class DatasetModality(StrEnum):
    BULK_RNASEQ = "bulk_rnaseq"
    MICROARRAY = "microarray"
    GENERIC_EXPRESSION = "generic_expression"


class DatasetSourceKind(StrEnum):
    FASTQ = "fastq"
    COUNT_MATRIX = "count_matrix"
    SALMON_QUANT = "salmon_quant"
    AFFYMETRIX_CEL = "affymetrix_cel"
    NORMALIZED_MATRIX = "normalized_matrix"


class DatasetStatus(StrEnum):
    DRAFT = "draft"
    VALIDATING = "validating"
    VALID = "valid"
    INVALID = "invalid"
    PREPARING = "preparing"
    PREPARED = "prepared"


class RunType(StrEnum):
    DATASET_VALIDATION = "dataset_validation"
    DATASET_PREPARATION = "dataset_preparation"
    ANALYSIS = "analysis"
    PREDICTION = "prediction"
    ASSAY_EXPERIMENT = "assay_experiment"
    ASSAY_STUDY = "assay_study"


class RunState(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"


class AnalysisType(StrEnum):
    DIFFERENTIAL_EXPRESSION = "differential_expression"
    DIMENSION_REDUCTION = "dimension_reduction"
    CLASSIFIER = "classifier"
    SIGNATURE = "signature"
    DECONVOLUTION = "deconvolution"


class AssayLifecycleStage(StrEnum):
    DEFINE = "DEFINE"
    FEASIBILITY = "FEASIBILITY"
    EXPLORE = "EXPLORE"
    OPTIMIZE = "OPTIMIZE"
    DEVELOP = "DEVELOP"
    LOCK = "LOCK"
    VALIDATE = "VALIDATE"
    REPORT = "REPORT"
    ON_HOLD = "ON_HOLD"
    COMPLETED = "COMPLETED"


class AssayReadinessStatus(StrEnum):
    NOT_ASSESSED = "NOT_ASSESSED"
    BLOCKED = "BLOCKED"
    NEEDS_INFORMATION = "NEEDS_INFORMATION"
    READY_FOR_RECOMMENDED_ACTION = "READY_FOR_RECOMMENDED_ACTION"
    ACTION_IN_PROGRESS = "ACTION_IN_PROGRESS"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class QuestionSource(StrEnum):
    USER_SELECTED = "USER_SELECTED"
    SYSTEM_RECOMMENDED = "SYSTEM_RECOMMENDED"
    FOLLOW_UP_FROM_RESULT = "FOLLOW_UP_FROM_RESULT"


class RecommendationRequirement(StrEnum):
    BLOCKER = "BLOCKER"
    STRONGLY_RECOMMENDED = "STRONGLY_RECOMMENDED"
    RECOMMENDED = "RECOMMENDED"
    OPTIONAL = "OPTIONAL"
    NOT_RECOMMENDED = "NOT_RECOMMENDED"


class RecommendationStatus(StrEnum):
    OPEN = "OPEN"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    SUPERSEDED = "SUPERSEDED"
    COMPLETED = "COMPLETED"


class DevelopmentExperimentType(StrEnum):
    TECHNICAL_FEASIBILITY = "TECHNICAL_FEASIBILITY"
    PAIRED_CONDITION_COMPARISON = "PAIRED_CONDITION_COMPARISON"
    MULTIFACTOR_OPTIMIZATION = "MULTIFACTOR_OPTIMIZATION"
    INPUT_DEGRADATION_EXPLORATION = "INPUT_DEGRADATION_EXPLORATION"
    SEQUENCING_DEPTH_EXPLORATION = "SEQUENCING_DEPTH_EXPLORATION"
    VARIANCE_SOURCE_INVESTIGATION = "VARIANCE_SOURCE_INVESTIGATION"
    QC_RULE_EVALUATION = "QC_RULE_EVALUATION"
    BATCH_CONFOUNDER_INVESTIGATION = "BATCH_CONFOUNDER_INVESTIGATION"


class DevelopmentExperimentStatus(StrEnum):
    DRAFT = "DRAFT"
    DESIGN_VALID = "DESIGN_VALID"
    DESIGN_INVALID = "DESIGN_INVALID"


class AnalyticalStudyType(StrEnum):
    PRECISION_REPRODUCIBILITY = "PRECISION_REPRODUCIBILITY"
    INPUT_DEGRADATION_LIMIT = "INPUT_DEGRADATION_LIMIT"
    PAIRED_BRIDGING = "PAIRED_BRIDGING"
    ROBUSTNESS_INTERFERENCE = "ROBUSTNESS_INTERFERENCE"


class AnalyticalStudyStatus(StrEnum):
    DRAFT = "DRAFT"
    DESIGN_VALID = "DESIGN_VALID"
    DESIGN_INVALID = "DESIGN_INVALID"
    LOCKED = "LOCKED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    SUPERSEDED = "SUPERSEDED"
